In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
import tensorflow as tf
print(tf.__version__)


2.20.0


In [4]:
## Sentences

sent=[ 'The glass of milk',
      'the cup of tea',
      'the glass of juice',
      'I am a good girl',
      'I am a good developer',
      'I love Codingg',
      'Letssgooo'
]

In [5]:
sent

['The glass of milk',
 'the cup of tea',
 'the glass of juice',
 'I am a good girl',
 'I am a good developer',
 'I love Codingg',
 'Letssgooo']

In [6]:
voc_size= 10000

In [7]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]

In [ ]:
# like Here (the) word basically comed on 6974 index based on vector representation in 6974 index it will get 1 and rest will be 0.


one_hot_repr



[[6974, 1308, 4754, 3347],
 [6974, 8138, 4754, 7829],
 [6974, 1308, 4754, 6008],
 [2377, 789, 5032, 9721, 5099],
 [2377, 789, 5032, 9721, 1785],
 [2377, 8053, 3670],
 [3670]]

In [11]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences


In [12]:
import numpy as np

In [14]:
# Here we are doing padding because we need to give index of same size or input then only model works 

sent_lenght=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 6974 1308 4754 3347]
 [   0    0    0    0 6974 8138 4754 7829]
 [   0    0    0    0 6974 1308 4754 6008]
 [   0    0    0 2377  789 5032 9721 5099]
 [   0    0    0 2377  789 5032 9721 1785]
 [   0    0    0    0    0 2377 8053 3670]
 [   0    0    0    0    0    0    0 3670]]


In [15]:
# feature representation

dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_lenght))
model.compile('adam','mse')

c:\Users\Nida\Desktop\Deep Learning NLP\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[[ 0.03635671, -0.02934874,  0.00283747, -0.04804434,
          0.00189941,  0.02180611,  0.0283515 , -0.04389911,
         -0.0199037 ,  0.01813629],
        [ 0.03635671, -0.02934874,  0.00283747, -0.04804434,
          0.00189941,  0.02180611,  0.0283515 , -0.04389911,
         -0.0199037 ,  0.01813629],
        [ 0.03635671, -0.02934874,  0.00283747, -0.04804434,
          0.00189941,  0.02180611,  0.0283515 , -0.04389911,
         -0.0199037 ,  0.01813629],
        [ 0.03635671, -0.02934874,  0.00283747, -0.04804434,
          0.00189941,  0.02180611,  0.0283515 , -0.04389911,
         -0.0199037 ,  0.01813629],
        [-0.03339151,  0.00177916,  0.01375799, -0.03861284,
          0.04545683, -0.02159253,  0.02225817,  0.00621242,
          0.02314681, -0.02005721],
        [ 0.03831644, -0.04415317, -0.02071825,  0.03495145,
         -0.00333004, -0.02455955,  0.00256068, -0.02521763,
         -0.00161967,  0.0205293 ],
        [-0.02945548, -0.0365006 , -0.04114746,  0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 6974, 1308, 4754, 3347], dtype=int32)